In [17]:
#Carregando bibliotecas e datasets
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os

users = pd.read_csv("../data/users_dataset.csv")
user_plan = pd.read_csv("../data/user_plan.csv")
user_app = pd.read_csv("../data/user_app.csv")
activities = pd.read_csv("../data/activities_dataset.csv")
weekly_visits = pd.read_csv("../data/weekly_gym_visits_aggregated_dataset.csv")
challenges = pd.read_csv("../data/challenges_dataset.csv")
desafio_usuario = pd.read_csv("../data/desafio_usuario_dataset.csv")

In [18]:
#Criando dicionário dos datasets
datasets = {
    'users': users,
    'user_plan': user_plan,
    'user_app': user_app,
    'activities': activities,
    'weekly_visits': weekly_visits,
    'challenges': challenges,
    'desafio_usuario': desafio_usuario
}

In [19]:
#Verificando tipos de dados para confirmação
for name, df in datasets.items():
    print(f'\n==== {name} ====')
    print(df.dtypes)

==== users ====
user_id              int64
age_group              str
gender                 str
distance_to_gym    float64
dtype: object

==== user_plan ====
user_id        int64
data_inicio      str
plano            str
dtype: object

==== user_app ====
user_id      int64
checkin        str
atividade      str
post         int64
dtype: object

==== activities ====
activity_id            int64
user_id                int64
steps                  int64
minutes_meditated      int64
activity_type            str
date                     str
calories_burned      float64
gym_visit               bool
week                   int64
dtype: object

==== weekly_visits ====
user_id              int64
week                 int64
weekly_gym_visits    int64
sedentarism_level    int64
dtype: object

==== challenges ====
id_desafio       int64
activity_type      str
data_inicio        str
data_fim           str
dtype: object

==== desafio_usuario ====
user_id         int64
desafio_id      int64
data_desafio      str
completou       int64
dtype: object

In [20]:
#Convertendo colunas de datas
user_plan['data_inicio'] = pd.to_datetime(user_plan['data_inicio'])

user_app['checkin'] = pd.to_datetime(user_app['checkin'])

activities['date'] = pd.to_datetime(activities['date'])

challenges['data_inicio'] = pd.to_datetime(challenges['data_inicio'])
challenges['data_fim'] = pd.to_datetime(challenges['data_fim'])

desafio_usuario['data_desafio'] = pd.to_datetime(desafio_usuario['data_desafio'])

In [21]:
#Verificando novamente os tipos de dados após ajustes
for name, df in datasets.items():
    print(f'\n==== {name} ====')
    print(df.dtypes)

==== users ====
user_id              int64
age_group              str
gender                 str
distance_to_gym    float64
dtype: object

==== user_plan ====
user_id                 int64
data_inicio    datetime64[us]
plano                     str
dtype: object

==== user_app ====
user_id               int64
checkin      datetime64[us]
atividade               str
post                  int64
dtype: object

==== activities ====
activity_id                   int64
user_id                       int64
steps                         int64
minutes_meditated             int64
activity_type                   str
date                 datetime64[us]
calories_burned             float64
gym_visit                      bool
week                          int64
dtype: object

==== weekly_visits ====
user_id              int64
week                 int64
weekly_gym_visits    int64
sedentarism_level    int64
dtype: object

==== challenges ====
id_desafio                int64
activity_type               str
data_inicio      datetime64[us]
data_fim         datetime64[us]
dtype: object

==== desafio_usuario ====
user_id                  int64
desafio_id               int64
data_desafio    datetime64[us]
completou                int64
dtype: object

In [22]:
#Verificando tamanho do dataset
df.shape

(500, 4)

In [23]:
#Verificando duplicatas dos dados novamente para confirmação   
for name, df in datasets.items():
    print(f'{name}: {df.duplicated().sum()} duplicadas')

users: 0 duplicadas
user_plan: 2 duplicadas
user_app: 24 duplicadas
activities: 0 duplicadas
weekly_visits: 0 duplicadas
challenges: 0 duplicadas
desafio_usuario: 4 duplicadas

In [24]:
#Removendo duplicatas
user_plan = user_plan.drop_duplicates()

user_app = user_app.drop_duplicates()

desafio_usuario = desafio_usuario.drop_duplicates()

In [25]:
#Verificando duplicatas novamente após correção
desafio_usuario.duplicated().sum()

user_app.duplicated().sum()

desafio_usuario.duplicated().sum()

np.int64(0)

In [26]:
for name, df in datasets.items():

    print(f'\n==== Dataset: {name} ====')

    for col in df.columns:
        min_val = df[col].min()
        max_val = df[col].max()

        print(f'{col}: min = {min_val} | max = {max_val}')

==== Dataset: users ====
user_id: min = 1 | max = 1000
age_group: min = 18-25 | max = 51+
gender: min = Female | max = Non-binary
distance_to_gym: min = 0.0 | max = 49.89

==== Dataset: user_plan ====
user_id: min = 1 | max = 1000
data_inicio: min = 2023-01-01 00:00:00 | max = 2024-08-24 00:00:00
plano: min = Grátis | max = Pagante

==== Dataset: user_app ====
user_id: min = 1 | max = 1000
checkin: min = 2023-01-01 00:00:00 | max = 2024-11-30 00:00:00
atividade: min = Bike Indoor | max = Meditação
post: min = 0 | max = 1

==== Dataset: activities ====
activity_id: min = 1 | max = 13144
user_id: min = 1 | max = 1000
steps: min = 3 | max = 19999
minutes_meditated: min = 0 | max = 59
activity_type: min = Bike Indoor | max = Meditação
date: min = 2023-01-01 00:00:00 | max = 2024-11-30 00:00:00
calories_burned: min = 10.0 | max = 999.99
gym_visit: min = False | max = True
week: min = 1 | max = 52

==== Dataset: weekly_visits ====
user_id: min = 1 | max = 1000
week: min = 1 | max = 52
weekly_gym_visits: min = 0 | max = 13
sedentarism_level: min = 0 | max = 5

==== Dataset: challenges ====
id_desafio: min = 1 | max = 50
activity_type: min = Bike Indoor | max = Meditação
data_inicio: min = 2023-08-01 00:00:00 | max = 2024-07-09 00:00:00
data_fim: min = 2023-08-08 00:00:00 | max = 2024-07-16 00:00:00

==== Dataset: desafio_usuario ====
user_id: min = 3 | max = 988
desafio_id: min = 1 | max = 50
data_desafio: min = 2023-08-01 00:00:00 | max = 2024-07-09 00:00:00
completou: min = 0 | max = 1

In [27]:
activities[['steps','minutes_meditated','calories_burned']].agg(['min','max'])

     steps  minutes_meditated  calories_burned
min      3                  0            10.00
max  19999                 59           999.99

Supondo que dependendo do tipo de atividade, a quantidade de steps e calories_burned podem estar ok, assim como o tempo!

In [28]:
#Verificando valores inconsistentes
users[users['distance_to_gym'] < 0]

activities[activities['steps'] < 0]
activities[activities['minutes_meditated'] < 0]
activities[activities['calories_burned'] < 0]

weekly_visits[weekly_visits['weekly_gym_visits'] < 0]
weekly_visits[weekly_visits['weekly_gym_visits'] > 7]

      user_id  week  weekly_gym_visits  sedentarism_level
672        73     5                 13                  5
682        73    52                 10                  5
5454      560    48                  8                  5
5791      596     9                  8                  5
8036      825    28                 10                  5

In [29]:
weekly_visits['weekly_gym_visits'].value_counts().sort_index()

weekly_gym_visits
0     4302
1     4434
2      218
3      352
4       32
5      353
6       38
7        1
8        2
10       2
13       1
Name: count, dtype: int64

Por não se tratarem de visitas a acadêmia com valores muito discrepantes a 7 (quantidade de dias da semana), não será excluído esses dados, pois irei assumir que certas pessoas podem fazer mais de 1 checkin por dia, por exemplo, aumentando esse número.

In [30]:
# Verificando integridade dos dados
datasets_user = {
    'user_plan': user_plan,
    'user_app': user_app,
    'activities': activities,
    'weekly_visits': weekly_visits,
    'desafio_usuario': desafio_usuario
}

for name, df in datasets_user.items():

    missing_users = set(df['user_id']) - set(users['user_id'])

    print(f'{name}: {len(missing_users)} user_id inconsistentes')

user_plan: 0 user_id inconsistentes
user_app: 0 user_id inconsistentes
activities: 0 user_id inconsistentes
weekly_visits: 0 user_id inconsistentes
desafio_usuario: 0 user_id inconsistentes

In [31]:
set(desafio_usuario['desafio_id']) - set(challenges['id_desafio'])

set()

In [32]:
#Salvando datasets limpos
os.makedirs("../data/processed", exist_ok=True)

users.to_csv("../data/processed/users_clean.csv", index=False)
user_plan.to_csv("../data/processed/user_plan_clean.csv", index=False)
user_app.to_csv("../data/processed/user_app_clean.csv", index=False)
activities.to_csv("../data/processed/activities_clean.csv", index=False)
weekly_visits.to_csv("../data/processed/weekly_visits_clean.csv", index=False)
challenges.to_csv("../data/processed/challenges_clean.csv", index=False)
desafio_usuario.to_csv("../data/processed/desafio_usuario_clean.csv", index=False)